//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jda_product_lot.LSLIpWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="LSLIpWebService.zdk_server2")]
    public interface zdk_server2 {
        
        // CODEGEN: 操作 ZDATA_TO_SAP_SYNC2 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zdk_server2:ZDATA_TO_SAP_SYNC2Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1 ZDATA_TO_SAP_SYNC2(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zdk_server2:ZDATA_TO_SAP_SYNC2Request", ReplyAction="*")]
        System.Threading.Tasks.Task<jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1> ZDATA_TO_SAP_SYNC2Async(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZDATA_TO_SAP_SYNC2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iN_JSONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IN_JSON {
            get {
                return this.iN_JSONField;
            }
            set {
                this.iN_JSONField = value;
                this.RaisePropertyChanged("IN_JSON");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZDATA_TO_SAP_SYNC2Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oUT_JSONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OUT_JSON {
            get {
                return this.oUT_JSONField;
            }
            set {
                this.oUT_JSONField = value;
                this.RaisePropertyChanged("OUT_JSON");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZDATA_TO_SAP_SYNC2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2 ZDATA_TO_SAP_SYNC2;
        
        public ZDATA_TO_SAP_SYNC2Request() {
        }
        
        public ZDATA_TO_SAP_SYNC2Request(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2 ZDATA_TO_SAP_SYNC2) {
            this.ZDATA_TO_SAP_SYNC2 = ZDATA_TO_SAP_SYNC2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZDATA_TO_SAP_SYNC2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response ZDATA_TO_SAP_SYNC2Response;
        
        public ZDATA_TO_SAP_SYNC2Response1() {
        }
        
        public ZDATA_TO_SAP_SYNC2Response1(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response ZDATA_TO_SAP_SYNC2Response) {
            this.ZDATA_TO_SAP_SYNC2Response = ZDATA_TO_SAP_SYNC2Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zdk_server2Channel : jda_product_lot.LSLIpWebService.zdk_server2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zdk_server2Client : System.ServiceModel.ClientBase<jda_product_lot.LSLIpWebService.zdk_server2>, jda_product_lot.LSLIpWebService.zdk_server2 {
        
        public zdk_server2Client() {
        }
        
        public zdk_server2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zdk_server2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zdk_server2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zdk_server2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1 jda_product_lot.LSLIpWebService.zdk_server2.ZDATA_TO_SAP_SYNC2(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request request) {
            return base.Channel.ZDATA_TO_SAP_SYNC2(request);
        }
        
        public jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response ZDATA_TO_SAP_SYNC2(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2 ZDATA_TO_SAP_SYNC21) {
            jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request inValue = new jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request();
            inValue.ZDATA_TO_SAP_SYNC2 = ZDATA_TO_SAP_SYNC21;
            jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1 retVal = ((jda_product_lot.LSLIpWebService.zdk_server2)(this)).ZDATA_TO_SAP_SYNC2(inValue);
            return retVal.ZDATA_TO_SAP_SYNC2Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1> jda_product_lot.LSLIpWebService.zdk_server2.ZDATA_TO_SAP_SYNC2Async(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request request) {
            return base.Channel.ZDATA_TO_SAP_SYNC2Async(request);
        }
        
        public System.Threading.Tasks.Task<jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Response1> ZDATA_TO_SAP_SYNC2Async(jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2 ZDATA_TO_SAP_SYNC2) {
            jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request inValue = new jda_product_lot.LSLIpWebService.ZDATA_TO_SAP_SYNC2Request();
            inValue.ZDATA_TO_SAP_SYNC2 = ZDATA_TO_SAP_SYNC2;
            return ((jda_product_lot.LSLIpWebService.zdk_server2)(this)).ZDATA_TO_SAP_SYNC2Async(inValue);
        }
    }
}
