//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebService.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.apache.org/axis2/services/SVCUserManager/", ConfigurationName="ServiceReference2.erpservicePortType")]
    public interface erpservicePortType {
        
        // CODEGEN: 消息 incaWsRequest 的包装命名空间(http://inca.com)以后生成的消息协定与默认值(http://ws.apache.org/axis2/services/SVCUserManager/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:incaWs", ReplyAction="urn:incaWsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestWebService.ServiceReference2.incaWsResponse incaWs(TestWebService.ServiceReference2.incaWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:incaWs", ReplyAction="urn:incaWsResponse")]
        System.Threading.Tasks.Task<TestWebService.ServiceReference2.incaWsResponse> incaWsAsync(TestWebService.ServiceReference2.incaWsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="incaWs", WrapperNamespace="http://inca.com", IsWrapped=true)]
    public partial class incaWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inca.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inca.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string jsonstr;
        
        public incaWsRequest() {
        }
        
        public incaWsRequest(string type, string jsonstr) {
            this.type = type;
            this.jsonstr = jsonstr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="incaWsResponse", WrapperNamespace="http://inca.com", IsWrapped=true)]
    public partial class incaWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inca.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public incaWsResponse() {
        }
        
        public incaWsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface erpservicePortTypeChannel : TestWebService.ServiceReference2.erpservicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class erpservicePortTypeClient : System.ServiceModel.ClientBase<TestWebService.ServiceReference2.erpservicePortType>, TestWebService.ServiceReference2.erpservicePortType {
        
        public erpservicePortTypeClient() {
        }
        
        public erpservicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public erpservicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public erpservicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public erpservicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReference2.incaWsResponse TestWebService.ServiceReference2.erpservicePortType.incaWs(TestWebService.ServiceReference2.incaWsRequest request) {
            return base.Channel.incaWs(request);
        }
        
        public string incaWs(string type, string jsonstr) {
            TestWebService.ServiceReference2.incaWsRequest inValue = new TestWebService.ServiceReference2.incaWsRequest();
            inValue.type = type;
            inValue.jsonstr = jsonstr;
            TestWebService.ServiceReference2.incaWsResponse retVal = ((TestWebService.ServiceReference2.erpservicePortType)(this)).incaWs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReference2.incaWsResponse> TestWebService.ServiceReference2.erpservicePortType.incaWsAsync(TestWebService.ServiceReference2.incaWsRequest request) {
            return base.Channel.incaWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReference2.incaWsResponse> incaWsAsync(string type, string jsonstr) {
            TestWebService.ServiceReference2.incaWsRequest inValue = new TestWebService.ServiceReference2.incaWsRequest();
            inValue.type = type;
            inValue.jsonstr = jsonstr;
            return ((TestWebService.ServiceReference2.erpservicePortType)(this)).incaWsAsync(inValue);
        }
    }
}
